### PR TITLE
Transform path with string or matrix type

### PR DESCRIPTION
**Pull request by duncanwerner**
This library is great. I am using it to do SVG rendering in a PDF with [pdf-lib][1]. For this application I have paths and I have (potentially stacked) SVG transform attributes, so I want to transform using those attributes directly.

Let me use the transform as a string, so I don't have to decompose it. 

I also want to cache transforms. For that I could use strings, but I would prefer to pass in CSSMatrix instances directly, so the transforms don't have to be reparsed. But I understand why you might not want to do that, to avoid leaking that type.

[1]: https://github.com/vanielf/pdf-lib

### CODE REVIEW

**Comment by thednp** [comment]
@duncanwerner thank you for your PR, much appreciated!

At first I was happy to see interest going up in here, almost about to approve your PR, however, you can't just do `matrixInstance = new CSSMatrix(transform);` or `matrixInstance = transform;` simply because this won't be consistent with the SVG coordinate system (which is still a totally different thing) and that is why we always parse values and pass them to `getSVGMatrix()` (if values are correct).

**Comment by duncanwerner** [comment]
Can you give me an example of when this would be inconsistent? Just looking at the string case, what would be the difference between passing in `{ translate: [10, 10] }` vs a string transform attribute `"translate (10 10)"`?

I know I ignored transform origin, but that seems like a different problem.

**Comment by thednp** [comment]
It's not immediately apparent, but when you use rotations/skews you always circle back to origin. Don't get me wrong I put a lot of thought into it, even considered something similar to your PR changes.

The real problem is that allowing the passing of a string or CSSMatrix/DOMMatrix instance would be confusing to new users when it comes to SVG metrics and even myself as well as yourself, especially because the default origin is `[0,0,0]` for the `transformPath` and `[50% shape width, 50% shape height, 50% shape width]` for the SVGPathCommander class (a deliberate design decision, mentioned in the docs).

While you can absolutely do what `getSVGMatrix()` does starting from a CSSMatrix/DOMMatrix instance, the same does not apply to string values, which automatically disqualify these changes.

I can see this PR might be appealing in many ways, I just can't figure who would actually benefit besides you. In my mind ATM I'm thinking of a wrapper around `transformPath` and a combination with [parseTransformString()](https://github.com/thednp/kute.js/blob/master/src/components/svgTransform.js#L25-L42) might actually be the thing you're looking for, what do you think?

**Comment by duncanwerner** [comment]
> I just can't figure who would actually benefit besides you

Haha. Probably right. `parseTransformString` would work, but as far as I can tell it does not accept a matrix, correct? That's the only nontrivial case, and the primary reason I wanted to pass in strings.

**Comment by thednp** [comment]
So @duncanwerner we can close this somehow?

**Comment by duncanwerner** [comment]
Sure, go ahead and close it. I am just going to use my fork.

**Pull request closed without merging**
